package com.github.timgoes1997.paypal;

import org.glassfish.jersey.media.multipart.MultiPartFeature;
import org.glassfish.jersey.server.ResourceConfig;

import javax.ws.rs.ApplicationPath;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@ApplicationPath("/api/")
public class App  extends ResourceConfig {
    public App() {
        packages("com.github.timgoes1997.paypal");
        register(MultiPartFeature.class);
    }
}
